#!/bin/bash

# Install dotfiles with stow
#
# http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html

function install () {
  PKGNAME=$1
  echo "Installing dotfiles for $PKGNAME"
  stow $PKGNAME
}

cd ~/dotfiles

PKGNAME=$1

if [ "$PKGNAME" = "" ]
then
  echo -e "Installing all dotfiles\n\n"
  for PKGDIR in `find . -not -path '*/\.*' -type d -d 1`
  do
    install ${PKGDIR:2}
  done
else
  install $PKGNAME
fi
