#!/usr/bin/env bash

# Install dotfiles with stow - http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html

SRC_DIR=${1:-$DOTFILES_DIR}

for PKGDIR in `find $SRC_DIR -not -path '*/\.*' -type d -d 1`
do
  if [ -d "$PKGDIR/home" ]
  then
    PKGNAME=${PKGDIR#$SRC_DIR/}
    echo "Installing dotfiles for $PKGNAME"
    stow -R --dir=$PKGDIR --target=$HOME home
  fi
done
