source "$DOTFILES_DIR/env"

BASH="$DOTFILES_DIR/bash"

source "$BASH/env"
source "$BASH/functions"
source "$BASH/aliases"

source dotfiles-sh "$DOTFILES_DIR"

[ -f "$DOTFILES_EXTRA_DIR/extra.bash" ] && source "$DOTFILES_EXTRA_DIR/extra.bash"
